// export const SET_ROOT_PATH = 'SET_ROOT_PATH' // 设置根地址

export const SET_CLICK_FILE_PATH = 'SET_CLICK_FILE_PATH'
export const SET_CLICK_FILE_OBJ = 'SET_CLICK_FILE_OBJ'
export const SET_INPUT_VISIBLE = 'SET_INPUT_VISIBLE'
export const SET_CURRENT_DIR_PATH = 'SET_CURRENT_DIR_PATH' // 设置当前目录路径
export const ADD_FILE_BAR_ITEM = 'ADD_FILE_BAR_ITEM'
export const SET_CURRENT_SHOW_FILE = 'SET_CURRENT_SHOW_FILE'// 设置当前打开的文件路径
export const SET_OPEN_FILE_OBJ = 'SET_OPEN_FILE_OBJ'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const UPDATE_CONTENT = 'UPDATE_CONTENT'

export const SET_EDITABLE = 'SET_EDITABLE'
export const SET_CREATE_TYPE = 'SET_CREATE_TYPE'

export const SET_CURRENT_DIR_OBJ = 'SET_CURRENT_DIR_OBJ'
export const UPDATE_CURRENT_DIR_OBJ_FOLD = 'UPDATE_CURRENT_DIR_OBJ_FOLD'

